URL = "https://eplus.jp/aqours-finale-cd"
# The entry page for the event you apply to
# This is currently working only for love live serial events

[[Ballots]]
Credentials = { username = "an@example.com", password = "NonakaCocona" }
# The login info for your eplus account

Codes = ["aaa", "bbb"]
# All the codes you want to apply for this specific account

Sessions = "All"
# You can specify a list or you can just write "All" if you want to apply for all sessions.
# Supported options are: "昼公演", "夜公演", "Day.1", "Day.2", and "All"
# Examples:
# Sessions = ["昼公演"]
# Sessions = ["昼公演", "夜公演"]
# Sessions = "All"

Renban = 1 # or { name = "ふううばる", address = "mail@address.com" }
# If you don't want to ballot with a renban you can either comment the line
# or put the value 0 or the value -1
# If your renban list is A, B, C, ..., the value you should pick is:
# A -> 1
# B -> 2
# C -> 3
# ...
# You can also find this as the "No" of the person on
# https://member.eplus.jp/update-dokosha
# You can also specify the renban by his name and address as a mapping as seen above
# copy the "同行者名" without any spaces into the "name" field
# and "メールアドレス" to the address key

ShippingInfo = [] # If you don't want goods, keep it empty aka only the: [] or comment out the line completely
# if you want goods you need to fill your information in a very specific order:
# [Name, Phone, zip, Prefecture, City, Address 1, Address 2]
# 1. Full Name in full-width characters
# 2. Phone number in half-width characters
# 3. zip code in half-width characters
# 4. Prefecture in full-width characters
# 5. City in full-width characters
# 6. Address 1 in full-width characters
# 7. Address 2 in full-width characters
# e.g., GoodsInfo = ["ＦＯＯ　ＢＡＲ", "+815050505050", "123-0123", "ＴＯＫＹＯ", "ＡＫＩＨＡＢＡＲＡ", "ＡＤＤＲＥＳＳ　１"，　"ＡＤＤＲＥＳＳ ２"]
